Made Results card responsive to the device size
MLH-Fellowship/prep-project-23.MAR.PREP.2 pull request #19
Opened 2023-03-16 22:09 UTC by tapaswini-kodavanti

2023-03-17 00:01 UTC, utk09 requested changes
Good work - please check the review comments

2023-03-17 00:01 UTC, utk09 commented on src/App.css
> +  margin-top: 5%;
Really clever solution, like it.

But on mobile phones, the card becomes smaller and the search bar is little too narrow. Can we please add `@media queries` to accommodate for various screen sizes?

Along with that, I think an appropriate solution would also be to cater all elements that are going to come on the page - like map and news cards. I would suggest reaching out to fellows who are working on these items and see what page size would be perfect for all elements to come on the page without writing repetitive CSS.

2023-03-17 00:01 UTC, utk09 commented on example.env
> +REACT_APP_APIKEY=""
Does this need to be empty inverted comma? Can we remove it?

2023-03-22 22:20 UTC, isalyu commented
(1) This is very picky; and maybe this wouldn't look better, but to me (again this a design comment), I think the input bar feels a little wider than needed in full screen mode (on laptop)

2023-03-22 23:46 UTC, utk09 commented
> (1) This is very picky; and maybe this wouldn't look better, but to me (again this a design comment), I think the input bar feels a little wider than needed in full screen mode (on laptop)

Please do implement this @tapaswini-kodavanti

2023-03-23 22:40 UTC, merged