The setting of weather based on location
MLH-Fellowship/prep-project-23.MAR.PREP.2 pull request #23
Opened 2023-03-18 03:55 UTC by carghai

This is Ekam Ghai PR on the auto setting of location, issue 5

2023-03-20 20:29 UTC, utk09 requested changes
Please check the review comments

2023-03-20 20:29 UTC, utk09 commented on src/App.js
> +                const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=YOUR_API_KEY`);
`&key=YOUR_API_KEY` --> this needs the API Key which is missing, please add that

2023-03-20 20:29 UTC, utk09 commented on src/App.js
> +                    }
Please add high-level comments defining what these lines of code do and how do they function

2023-03-22 17:46 UTC, TharunKumarReddyPolu requested changes
Great implementation of the feature and appreciate your hard work. Please check the review comments and also include necessary comments which define what a particular piece of code in there does!

2023-03-22 17:46 UTC, TharunKumarReddyPolu commented on src/App.js
> +import city from "city";
Code improvement Suggestion: You can use single quotes instead of double quotes to make it more aligned with other imports.

2023-03-22 17:46 UTC, TharunKumarReddyPolu commented on src/App.js
> +    const [city, setCity] = useState("New York City")
You can include a semicolon(;) at the end of the 9th line of code.

2023-03-22 17:46 UTC, TharunKumarReddyPolu commented on src/App.js
> +        fetch("https://api.openweathermap.org/data/2.5/weather?q=" + city + "&units=metric" + "&appid=" + process.env.REACT_APP_APIKEY)
Code improvement Suggestion: You can use template literals(backticks) for string concatenation.

2023-03-22 23:49 UTC, utk09 commented
I think all the fixes suggested are easy fix and align with the code structure of the repo, so please implement them @carghai 
Also please resolve the merge conflicts

2023-03-24 02:08 UTC, carghai commented
ok!

2023-03-24 02:51 UTC, closed without merging